name: Scheduled update

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download last RTE EcoWatt feed
        run: |
          echo ${{ secrets.RTE_CREDENTIAL }}
          RTE_OAUTH_RESULT=$(curl -sLS "https://digital.iservices.rte-france.com/token/oauth/" -H "Authorization: Basic ${{ secrets.RTE_CREDENTIAL }}")
          echo $RTE_OAUTH_RESULT
          RTE_ACCESS_TOKEN=$(echo $RTE_OAUTH_RESULT | jq -j '.access_token')
          echo $RTE_ACCESS_TOKEN
          curl "https://digital.iservices.rte-france.com/open_api/ecowatt/v4/signals" -H "Authorization: Bearer $RTE_ACCESS_TOKEN" | jq . > file/ecowatt.json
      - name: Commit and push changes
        run: |-
          git config user.name "Bot"
          git diff --quiet || (git add file/ecowatt.json && git commit -m "Updated with latest Ecowatt file")
          git push
          
