name: Scheduled update

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download Feed
        run: |-
          curl "https://ecoresponsable.numerique.gouv.fr/publications/referentiel-general-ecoconception/export/referentiel-general-ecoconception-version-beta.json" | jq . > file/rgesn.json
      - name: Commit and push changes
        run: |-
          git config user.name "Bot"
          git diff --quiet || (git add file/rgesn.json && git commit -m "Updated with latest RGESN file")
          git push
          
